
package com.wzitech.gamegold.common.insurance.dto;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-09T16:07:09.688+08:00
 * Generated source version: 3.1.0
 * 
 */
public final class BQOrderServiceSoap_BQOrderServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "BQOrderService");

    private BQOrderServiceSoap_BQOrderServiceSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BQOrderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BQOrderService ss = new BQOrderService(wsdlURL, SERVICE_NAME);
        BQOrderServiceSoap port = ss.getBQOrderServiceSoap();  
        
        {
        System.out.println("Invoking queryBQOrderByPiccNo...");
        String _queryBQOrderByPiccNo_piccNo = "";
        BackDTOToActivity _queryBQOrderByPiccNo__return = port.queryBQOrderByPiccNo(_queryBQOrderByPiccNo_piccNo);
        System.out.println("queryBQOrderByPiccNo.result=" + _queryBQOrderByPiccNo__return);


        }
        {
        System.out.println("Invoking queryBQ...");
        String _queryBQ_orderId = "";
        BackDTO _queryBQ__return = port.queryBQ(_queryBQ_orderId);
        System.out.println("queryBQ.result=" + _queryBQ__return);


        }
        {
        System.out.println("Invoking createBQOrder...");
        OrderDTO _createBQOrder_order = null;
        BackDTO _createBQOrder__return = port.createBQOrder(_createBQOrder_order);
        System.out.println("createBQOrder.result=" + _createBQOrder__return);


        }
        {
        System.out.println("Invoking cancerOrder...");
        String _cancerOrder_orderId = "";
        javax.xml.datatype.XMLGregorianCalendar _cancerOrder_cancerTime = null;
        BackDTO _cancerOrder__return = port.cancerOrder(_cancerOrder_orderId, _cancerOrder_cancerTime);
        System.out.println("cancerOrder.result=" + _cancerOrder__return);


        }
        {
        System.out.println("Invoking getBQOrderByOrderId...");
        String _getBQOrderByOrderId_orderId = "";
        BackDTOToActivity _getBQOrderByOrderId__return = port.getBQOrderByOrderId(_getBQOrderByOrderId_orderId);
        System.out.println("getBQOrderByOrderId.result=" + _getBQOrderByOrderId__return);


        }
        {
        System.out.println("Invoking modifyTransferTime...");
        String _modifyTransferTime_orderId = "";
        javax.xml.datatype.XMLGregorianCalendar _modifyTransferTime_transferTime = null;
        BackDTO _modifyTransferTime__return = port.modifyTransferTime(_modifyTransferTime_orderId, _modifyTransferTime_transferTime);
        System.out.println("modifyTransferTime.result=" + _modifyTransferTime__return);


        }
        {
        System.out.println("Invoking waitAuditBQ...");
        String _waitAuditBQ_orderId = "";
        String _waitAuditBQ_reason = "";
        BackDTO _waitAuditBQ__return = port.waitAuditBQ(_waitAuditBQ_orderId, _waitAuditBQ_reason);
        System.out.println("waitAuditBQ.result=" + _waitAuditBQ__return);


        }

        System.exit(0);
    }

}
