package com.wzitech.gamegold.common.insurance.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-09T16:07:09.731+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "BQOrderServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BQOrderServiceSoap {

    /**
     * 通过保单号查询订单信息
     */
    @WebResult(name = "QueryBQOrderByPiccNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryBQOrderByPiccNo", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.QueryBQOrderByPiccNo")
    @WebMethod(operationName = "QueryBQOrderByPiccNo", action = "http://tempuri.org/QueryBQOrderByPiccNo")
    @ResponseWrapper(localName = "QueryBQOrderByPiccNoResponse", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.QueryBQOrderByPiccNoResponse")
    public BackDTOToActivity queryBQOrderByPiccNo(
            @WebParam(name = "PiccNo", targetNamespace = "http://tempuri.org/")
            String piccNo
    );

    /**
     * 查询保单
     */
    @WebResult(name = "QueryBQResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryBQ", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.QueryBQ")
    @WebMethod(operationName = "QueryBQ", action = "http://tempuri.org/QueryBQ")
    @ResponseWrapper(localName = "QueryBQResponse", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.QueryBQResponse")
    public BackDTO queryBQ(
            @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
            String orderId
    );

    /**
     * 售后保障订单入口
     */
    @WebResult(name = "CreateBQOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateBQOrder", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.CreateBQOrder")
    @WebMethod(operationName = "CreateBQOrder", action = "http://tempuri.org/CreateBQOrder")
    @ResponseWrapper(localName = "CreateBQOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.CreateBQOrderResponse")
    public BackDTO createBQOrder(
            @WebParam(name = "order", targetNamespace = "http://tempuri.org/")
            OrderDTO order
    );

    /**
     * 订单撤销(点卡用)
     */
    @WebResult(name = "CancerOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancerOrder", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.CancerOrder")
    @WebMethod(operationName = "CancerOrder", action = "http://tempuri.org/CancerOrder")
    @ResponseWrapper(localName = "CancerOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.CancerOrderResponse")
    public BackDTO cancerOrder(
            @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
            String orderId,
            @WebParam(name = "CancerTime", targetNamespace = "http://tempuri.org/")
            javax.xml.datatype.XMLGregorianCalendar cancerTime
    );

    /**
     * 通过订单号查询订单信息
     */
    @WebResult(name = "GetBQOrderByOrderIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBQOrderByOrderId", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.GetBQOrderByOrderId")
    @WebMethod(operationName = "GetBQOrderByOrderId", action = "http://tempuri.org/GetBQOrderByOrderId")
    @ResponseWrapper(localName = "GetBQOrderByOrderIdResponse", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.GetBQOrderByOrderIdResponse")
    public BackDTOToActivity getBQOrderByOrderId(
            @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
            String orderId
    );

    /**
     * 转账时间
     */
    @WebResult(name = "ModifyTransferTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyTransferTime", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.ModifyTransferTime")
    @WebMethod(operationName = "ModifyTransferTime", action = "http://tempuri.org/ModifyTransferTime")
    @ResponseWrapper(localName = "ModifyTransferTimeResponse", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.ModifyTransferTimeResponse")
    public BackDTO modifyTransferTime(
            @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
            String orderId,
            @WebParam(name = "TransferTime", targetNamespace = "http://tempuri.org/")
            javax.xml.datatype.XMLGregorianCalendar transferTime
    );

    /**
     * 提出申保
     */
    @WebResult(name = "WaitAuditBQResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WaitAuditBQ", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.WaitAuditBQ")
    @WebMethod(operationName = "WaitAuditBQ", action = "http://tempuri.org/WaitAuditBQ")
    @ResponseWrapper(localName = "WaitAuditBQResponse", targetNamespace = "http://tempuri.org/", className = "com.wzitech.gamegold.common.insurance.dto.WaitAuditBQResponse")
    public BackDTO waitAuditBQ(
            @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
            String orderId,
            @WebParam(name = "reason", targetNamespace = "http://tempuri.org/")
            String reason
    );
}
