package com.wzitech.gamegold.common.insurance.dto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-09T16:07:09.747+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "BQOrderService", 
                  wsdlLocation = "http://admin.91baozhang.com/WebService/BQOrderService.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class BQOrderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "BQOrderService");
    public final static QName BQOrderServiceSoap12 = new QName("http://tempuri.org/", "BQOrderServiceSoap12");
    public final static QName BQOrderServiceSoap = new QName("http://tempuri.org/", "BQOrderServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://admin.91baozhang.com/WebService/BQOrderService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BQOrderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://admin.91baozhang.com/WebService/BQOrderService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public BQOrderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BQOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BQOrderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BQOrderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BQOrderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BQOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BQOrderServiceSoap
     */
    @WebEndpoint(name = "BQOrderServiceSoap12")
    public BQOrderServiceSoap getBQOrderServiceSoap12() {
        return super.getPort(BQOrderServiceSoap12, BQOrderServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BQOrderServiceSoap
     */
    @WebEndpoint(name = "BQOrderServiceSoap12")
    public BQOrderServiceSoap getBQOrderServiceSoap12(WebServiceFeature... features) {
        return super.getPort(BQOrderServiceSoap12, BQOrderServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns BQOrderServiceSoap
     */
    @WebEndpoint(name = "BQOrderServiceSoap")
    public BQOrderServiceSoap getBQOrderServiceSoap() {
        return super.getPort(BQOrderServiceSoap, BQOrderServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BQOrderServiceSoap
     */
    @WebEndpoint(name = "BQOrderServiceSoap")
    public BQOrderServiceSoap getBQOrderServiceSoap(WebServiceFeature... features) {
        return super.getPort(BQOrderServiceSoap, BQOrderServiceSoap.class, features);
    }

}
